development:
  adapter: mysql
  encoding: utf8
  database: bb_development
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql
  encoding: utf8
  database: bb_test
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  database: bb_production
  username: root
  password: damanuit
  socket: /var/run/mysqld/mysqld.sock
